### PR TITLE
Development

### PR DESCRIPTION
**Pull request by shandralor**

### CODE REVIEW

**Comment by shandralor** [comment]
Please review code so i can merge :-)

**Review by Lukas-Batema — CHANGES_REQUESTED** [review]
You may want to gitignore the `__pycache__` folders ;)

**Comment by Lukas-Batema** [comment]
Whoops, I assigned myself on accident...

**Comment by andrewstech** [comment]
> You may want to gitignore the `__pycache__` folders, as those change per-user and Python version used ;)

Yeah just that everything looks good.

**Comment by andrewstech** [comment]
It might be a good idea to add that to the .gitignore

**Comment by shandralor** [comment]
Changes to the pycache should be done

**Review by andrewstech — APPROVED** [review]

**Review by Lukas-Batema — CHANGES_REQUESTED** [review]
The root dir's `__pycache__/` can be removed as well.

**Comment by Lukas-Batema** [comment]
I also simplified the `.gitignore` `__pycache__` lines to one line, as it is in my branch on my fork.

**Review by Lukas-Batema — APPROVED** [review]
Looks good, for future reference, the `.gitignore` can have the 3 lines for ignoring this, into 1 line, as so
```txt
__pycache__/
```

**Comment by shandralor** [comment]
New app version with multiple bug fixes, email verification for account creation and password reset capability

**Pull request merged**
